new/delete/shell/dependencies/build/clean/deploy commands now accept 'package name' parameter

diff --git a/crossbuilder b/crossbuilder
--- a/crossbuilder
+++ b/crossbuilder
@@ -19,10 +19,9 @@
  
 
 # TODO:
-# BETTER THAN SBUILD
+# BEFORE WIDESPREAD PROMOTION
 # - support Debian package format 3.0 (quilt)
-# - document source command PACKAGE parameter
-# - make new/delete/shell/dependencies/build/clean/deploy accept 'package name' parameter
+# - document commands PACKAGE parameter
 # - support building multiple projects that depend on each other: crossbuilder PACKAGE1 PACKAGE2 PACKAGE3
 
 # PROJECT CUSTOMISATION - FASTER
@@ -61,7 +60,7 @@ display_help () {
     echo "    delete        - Delete a container."
 #    echo "    list          - List existing containers."
     echo "    shell         - Executes a shell in a container (will create it if needed)."
-#    echo "    source        - Download a source package from the repositories."
+    echo "    source        - Download a source package from the repositories."
     echo "    dependencies  - Download and install the dependencies of a package in a container (will create it if needed)"
     echo "    build         - Build a package in a container (will create it if needed)."
     echo "    clean         - Clean up the artifacts generated by a build."
@@ -236,8 +235,6 @@ shell_container () {
 
 get_source_package () {
     echo "${POSITIVE_COLOR}Downloading source package $PACKAGE for Ubuntu $TARGET_UBUNTU.${NC}"
-    mkdir -p $PACKAGE
-    cd $PACKAGE
     variables
     new_container
     OVERLAY_APT="/etc/apt/sources.list.d/ci-train-ppa-service-ubuntu-stable-phone-overlay-vivid.list"
@@ -515,25 +512,23 @@ if [ -z "$LXD_IMAGE" ] ; then
     LXD_IMAGE=sdk:ubuntu-sdk-$TARGET_UBUNTU-$HOST_ARCH-$TARGET_ARCH-dev
 fi
 
-if test -e debian/changelog ; then
-    PACKAGE=`dpkg-parsechangelog --show-field Source`
-    PACKAGE_VERSION=`dpkg-parsechangelog --show-field Version`
-fi
-
 COMMAND=$1
+shift
 if [ "$COMMAND" = "help" ] ; then
     display_help
     exit 0
 fi
 
+PACKAGE=$1
+if [ -n "$PACKAGE" ] ; then
+    mkdir -p $PACKAGE
+    cd $PACKAGE
+fi
 
-check_changelog_or_package () {
-    if [ -z "$PACKAGE" ] ; then
-        echo "${ERROR_COLOR}No debian/changelog found in the current directory.${NC}"
-        echo "If the source code is not available it can be automatically downloaded from the repositories using the 'source' command." 
-        exit 1
-    fi
-}
+if test -e debian/changelog ; then
+    PACKAGE=`dpkg-parsechangelog --show-field Source`
+    PACKAGE_VERSION=`dpkg-parsechangelog --show-field Version`
+fi
 
 check_command_parameter_count() {
     MIN_PARAMETERS=$1
@@ -553,8 +548,16 @@ check_command_parameter_count() {
     fi
 }
 
-ARGUMENTS=$@
-if [ -z "$ARGUMENTS" ] ; then
+check_changelog_or_package () {
+    if [ -z "$PACKAGE" ] ; then
+        echo "${ERROR_COLOR}No package specified and no debian/changelog found in the current directory.${NC}"
+        echo "If the source code is not available it can be automatically downloaded from the repositories using the 'source' command." 
+        exit 1
+    fi
+    check_command_parameter_count 0 1
+}
+
+if [ -z "$COMMAND" ] ; then
     check_changelog_or_package
     variables
     echo "${POSITIVE_COLOR}Building $PACKAGE for $TARGET_ARCH and deploying to device.${NC}"
@@ -563,10 +566,10 @@ if [ -z "$ARGUMENTS" ] ; then
     build
     deploy_to_device
 else
-    shift
     PARAMETERS=$@
     case "$COMMAND" in
         setup-lxd)
+            check_command_parameter_count 0 0
             if lxd_has_image_or_container ; then
                 echo "${POSITIVE_COLOR}You are already using LXD. To set it up again you must delete "
                 echo "all images and containers listed by 'lxc list' and 'lxc image list'.${NC}"
@@ -575,35 +578,29 @@ else
             setup_lxd
         ;;
         new)
-            check_command_parameter_count 0 0
             check_changelog_or_package
             variables
             new_container
         ;;
         delete)
-            check_command_parameter_count 0 0
             check_changelog_or_package
             variables
             delete_container
         ;;
         shell)
-            check_command_parameter_count 0 0
             check_changelog_or_package
             variables
             new_container
             shell_container
         ;;
         source)
-            PACKAGE=$1
             if [ -z "$PACKAGE" ] ; then
                 echo "${ERROR_COLOR}Command 'source' requires a package name: $PROGRAM_NAME source PACKAGE_NAME${NC}"
                 exit 1
             fi
-            check_command_parameter_count 1 1
             get_source_package
         ;;
         dependencies)
-            check_command_parameter_count 0 0
             check_changelog_or_package
             variables
             new_container
@@ -611,7 +608,6 @@ else
             install_dependencies
         ;;
         build)
-            check_command_parameter_count 0 0
             check_changelog_or_package
             variables
             new_container
@@ -619,13 +615,11 @@ else
             build
         ;;
         clean)
-            check_command_parameter_count 0 0
             check_changelog_or_package
             variables
             clean
         ;;
         deploy)
-            check_command_parameter_count 0 0
             check_changelog_or_package
             variables
             deploy_to_device
