added packages option

diff --git a/crossbuilder b/crossbuilder
--- a/crossbuilder
+++ b/crossbuilder
@@ -51,9 +51,10 @@ display_help () {
     echo "    clean         - Clean up the artifacts generated by a build."
     echo "    deploy        - Deploy a built package to a connected device."
 #    echo "    undeploy      - Remove previously deployed packages from a connected device."
-#    echo ""
-#    echo "Options:"
+    echo ""
+    echo "Options:"
 #    echo "  --verbose       - Print verbose information."
+    echo "  --packages       - Packages to deploy."
 }
 
 
@@ -75,7 +76,6 @@ exec_container () {
 }
 
 variables () {
-    PACKAGES_TO_DEPLOY=$@
     HOST_ARCH=`dpkg --print-architecture`
     TARGET_ARCH=armhf
     # FIXME: abort if no changelog is present
@@ -247,6 +247,31 @@ deploy_to_device () {
         exec_device "SUDO_ASKPASS=/tmp/askpass.sh sudo -A sed -i '/Pin-Priority/c\Pin-Priority: 1001' /etc/apt/preferences.d/extra-ppas.pref"
     fi;
 }
+
+
+while [ "$1" != "" ]; do
+    OPTION=`echo $1 | awk -F= '{print $1}'`
+    VALUE=`echo $1 | awk -F= '{print $2}'`
+    case $1 in
+        -*)
+            case $OPTION in
+            --packages)
+                PACKAGES_TO_DEPLOY=$VALUE
+            ;;
+            *)
+                display_help
+                echo ""
+                echo "${ERROR_COLOR}error: unknown option: $OPTION${NC}"
+                exit 1
+            ;;
+            esac
+            shift
+        ;;
+        *)
+            break
+        ;;
+    esac
+done
 
 ARGUMENTS=$@
 if [ -z "$ARGUMENTS" ] ; then
