added source command

diff --git a/crossbuilder b/crossbuilder
--- a/crossbuilder
+++ b/crossbuilder
@@ -16,7 +16,10 @@
  
 
 # TODO:
-# - support workflow using apt-get source
+# - make shell switch to user instead of root; perhaps add it to sudoers
+# - MAYBE: make shell depend on new; make dependencies depend on new; make build depend on new and dependencies
+# - document source command parameter
+# - make new/delete/shell accept 'package name' parameter
 # - support building multiple projects that depend on each other
 # - implement a 'make install' version
 # - support per project configuration; for example post deploy rules
@@ -45,6 +48,7 @@ display_help () {
     echo "    delete        - Delete a container."
 #    echo "    list          - List existing containers."
     echo "    shell         - Executes a shell in a container."
+    echo "    source        - Download a source package from the repositories."
     echo "    dependencies  - Download and install the dependencies of a package."
     echo "    build         - Build a package."
     echo "    clean         - Clean up the artifacts generated by a build."
@@ -162,6 +166,27 @@ delete_container () {
 shell_container () {
     echo "${POSITIVE_COLOR}Entering shell in LXD container $LXD_CONTAINER.${NC}"
     lxc exec $LXD_CONTAINER bash
+}
+
+get_source_package () {
+    echo "${POSITIVE_COLOR}Downloading source package $PACKAGE for Ubuntu $TARGET_UBUNTU.${NC}"
+    mkdir -p $PACKAGE
+    cd $PACKAGE
+    variables
+    new_container
+    OVERLAY_APT="/etc/apt/sources.list.d/ci-train-ppa-service-ubuntu-stable-phone-overlay-vivid.list"
+    if exec_container_root "grep '#.*deb-src' $OVERLAY_APT" ; then
+        exec_container_root "sed -i 's/#.*deb-src/deb-src/' $OVERLAY_APT"
+        # FIXME: without the sleep apt update fails for lack of internet connection
+        sleep 2
+        exec_container_root apt update
+    fi
+    lxc exec $LXD_CONTAINER -- su -l -c "cd $MOUNT_POINT; apt-get source $PACKAGE" $USERNAME
+    PACKAGE_VERSION=`dpkg-parsechangelog --show-field Version -l $PACKAGE*/debian/changelog`
+    rm -f $PACKAGE*.orig.tar.gz $PACKAGE*diff.gz $PACKAGE*.dsc
+    mv $PACKAGE-*/* .
+    rmdir $PACKAGE-*
+    echo "${POSITIVE_COLOR}Source code for $PACKAGE is now available in $PACKAGE/.${NC}"
 }
 
 install_dependencies () {
@@ -349,6 +374,15 @@ if [ "$COMMAND" = "help" ] ; then
     exit 0
 fi
 
+
+if [ "$COMMAND" != "source" ] ; then
+    if [ -z "$PACKAGE" ] ; then
+        echo "${ERROR_COLOR}No debian/changelog found in the current directory.${NC}"
+        echo "If the source code is not available it can be automatically downloaded from the repositories using the 'source' command." 
+        exit 1
+    fi
+fi
+
 ARGUMENTS=$@
 if [ -z "$ARGUMENTS" ] ; then
     variables
@@ -373,6 +407,14 @@ else
         shell)
             variables
             shell_container
+        ;;
+        source)
+            PACKAGE=$2
+            if [ -z "$PACKAGE" ] ; then
+                echo "${ERROR_COLOR}source requires a package name: $PROGRAM_NAME source PACKAGE_NAME${NC}"
+                exit 1
+            fi
+            get_source_package
         ;;
         dependencies)
             variables
