more robust lxd setup

diff --git a/crossbuilder b/crossbuilder
--- a/crossbuilder
+++ b/crossbuilder
@@ -47,7 +47,7 @@ display_help () {
     echo "Usage: $PROGRAM_NAME [options] [command]"
     echo "Available commands:"
     echo "    help          - Display this help."
-    echo "    setup         - Setup LXD. Needed before anything else."
+    echo "    setup-lxd     - Setup LXD. Needed before anything else."
     echo "    new           - Create a container to build in."
     echo "    delete        - Delete a container."
 #    echo "    list          - List existing containers."
@@ -111,9 +111,61 @@ variables () {
     SOURCE_PATH_CONTAINER=$MOUNT_POINT
 }
 
+check_lxd_accessible () {
+    if ! lxc info > /dev/null 2>&1 ; then
+        echo "${ERROR_COLOR}Please logout and login again then run '$PROGRAM_NAME setup-lxd'.${NC}"
+        exit 1
+    fi
+}
+
+lxd_has_image_or_container () {
+    CONTAINER_COUNT=$(lxc list | wc -l)
+    IMAGE_COUNT=$(lxc image list | wc -l)
+    if [ $CONTAINER_COUNT = "3" ] && [ $IMAGE_COUNT = "3" ]; then
+        return 1
+    fi
+
+    return 0
+}
+
+is_subuid_setup () {
+    if ! grep "root:1000:1" /etc/subuid > /dev/null ; then
+        return 1
+    fi
+    if ! grep "root:1000:1" /etc/subgid > /dev/null ; then
+        return 1
+    fi
+    return 0
+}
+
+ensure_lxd_subuid () {
+    if ! is_subuid_setup ; then
+        echo "${ERROR_COLOR}LXD requires subuid to be setup adequately to mount directories in containers.${NC}"
+        echo "${POSITIVE_COLOR}Would you like to do that now? (y/n) ${NC}"
+        read REPLY
+        echo
+        if [ "$REPLY" = y ]
+        then
+            sudo usermod --add-subuids 1000-1000 root
+            sudo usermod --add-subgids 1000-1000 root
+            sudo service lxd restart
+        else
+            exit 1
+        fi
+    fi
+}
+
 setup_lxd () {
+    if lxd_has_image_or_container ; then
+        echo "${POSITIVE_COLOR}You are already using LXD. To set it up again you must delete "
+        echo " all images and containers listed by 'lxc list' and 'lxc image list'."
+        return 0
+    fi
+
     echo "${POSITIVE_COLOR}Setting up LXD.${NC}"
-    echo -n "${POSITIVE_COLOR}Would you like to setup LXD with zfs in your home directory? (y/n) ${NC}"
+    echo -n "${POSITIVE_COLOR}Would you like to setup LXD with ZFS in your home directory? (y/n) \n${NC}"
+    echo -n "This is recommended for faster operation, and also in case there is not enough "
+    echo -n "space in your / partition. \n"
     read REPLY
     echo
     if [ "$REPLY" = y ]
@@ -131,12 +183,6 @@ setup_lxd () {
     else
         sudo lxd init --auto
     fi
-
-    sudo usermod --add-subuids 1000-1000 root
-    sudo usermod --add-subgids 1000-1000 root
-    sudo service lxd restart
-    echo "${ERROR_COLOR}LXD and $PROGRAM_NAME will only work from this terminal until you logout and login again.${NC}"
-    newgrp lxd
 }
 
 
@@ -349,12 +395,23 @@ if [ ! -z "$MISSING_PACKAGES" ] ; then
     sudo apt install $MISSING_PACKAGES
 fi
 
+
 if ! which lxd > /dev/null ; then
-    echo "${POSITIVE_COLOR}$PROGRAM_NAME uses LXD to download dependencies and build. Installing it now."
-    echo "sudo apt install lxd"
-    sudo apt install lxd
-    setup_lxd
+    echo "${POSITIVE_COLOR}$PROGRAM_NAME uses LXD to download dependencies and build."
+    echo -n "${POSITIVE_COLOR}Would you like to install LXD? (y/n) ${NC}"
+    read REPLY
+    echo
+    if [ "$REPLY" = y ]
+    then
+        sudo apt-get install -y lxd
+    else
+        echo "${ERROR_COLOR}$PROGRAM_NAME will not work without LXD. Bye.$OPTION${NC}"
+        exit 1
+    fi
 fi
+
+check_lxd_accessible
+ensure_lxd_subuid
 
 HOST_ARCH=`dpkg --print-architecture`
 TARGET_ARCH=armhf
@@ -413,16 +470,17 @@ if [ "$COMMAND" = "help" ] ; then
 fi
 
 
-if [ "$COMMAND" != "source" ] && [ "$COMMAND" != "setup" ] ; then
+check_changelog_or_package () {
     if [ -z "$PACKAGE" ] ; then
         echo "${ERROR_COLOR}No debian/changelog found in the current directory.${NC}"
         echo "If the source code is not available it can be automatically downloaded from the repositories using the 'source' command." 
         exit 1
     fi
-fi
+}
 
 ARGUMENTS=$@
 if [ -z "$ARGUMENTS" ] ; then
+    check_changelog_or_package
     variables
     echo "${POSITIVE_COLOR}Building $PACKAGE for $TARGET_ARCH and deploying to device.${NC}"
     new_container
@@ -431,18 +489,21 @@ if [ -z "$ARGUMENTS" ] ; then
     deploy_to_device
 else
     case "$COMMAND" in
-        setup)
+        setup-lxd)
             setup_lxd
         ;;
         new)
+            check_changelog_or_package
             variables
             new_container
         ;;
         delete)
+            check_changelog_or_package
             variables
             delete_container
         ;;
         shell)
+            check_changelog_or_package
             variables
             new_container
             shell_container
@@ -456,21 +517,25 @@ else
             get_source_package
         ;;
         dependencies)
+            check_changelog_or_package
             variables
             new_container
             install_dependencies
         ;;
         build)
+            check_changelog_or_package
             variables
             new_container
             install_dependencies
             build
         ;;
         clean)
+            check_changelog_or_package
             variables
             clean
         ;;
         deploy)
+            check_changelog_or_package
             variables
             deploy_to_device
         ;;
